language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PINS="github:. github-unix:. github-jsoo:."
   - DEPOPTS="github-unix github-jsoo"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.07 PACKAGE="github" REVDEPS=true
   - DISTRO=debian-testing OCAML_VERSION=4.06 PACKAGE="github-unix" REVDEPS=true
   - DISTRO=debian-unstable OCAML_VERSION=4.04 PACKAGE="github-unix"
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.05 PACKAGE="github-unix"
   - DISTRO=ubuntu-18.04 OCAML_VERSION=4.05 PACKAGE="github-unix"
   - DISTRO=centos-6 OCAML_VERSION=4.04 PACKAGE="github-unix"
   - DISTRO=centos-7 OCAML_VERSION=4.04 PACKAGE="github-unix"
   - DISTRO=fedora-28 OCAML_VERSION=4.04 PACKAGE="github-unix"
   - DISTRO=alpine OCAML_VERSION=4.03 PACKAGE="github-unix"
